#ifndef OS_TASK_INTERNAL_H
#define OS_TASK_INTERNAL_H
#include "os_def.h"
#include "os_sys.h"
#include "os_task_external.h"

#define OS_TASK_ERR_NO_FREE_CB OS_BUILD_ERR_CODE(OS_TASK_MID, 0x0)
#define OS_TASK_ERR_RESUME_STATUS_WRONG OS_BUILD_ERR_CODE(OS_TASK_MID, 0x1)
#define OS_TASK_ERR_CREATE_ALLOC_STACK_NO_MEM OS_BUILD_ERR_CODE(OS_TASK_MID, 0x2)
#define OS_TASK_ERR_DEL_NOT_READY OS_BUILD_ERR_CODE(OS_TASK_MID, 0x3)
#define OS_TASK_ERR_DEL_HOLDS_SEM OS_BUILD_ERR_CODE(OS_TASK_MID, 0x4)
#define OS_TASK_ERR_CREATE_PARAM_ILLEGAL OS_BUILD_ERR_CODE(OS_TASK_MID, 0x5)
#endif